### ISSUE TITLE
Mattdw UNI and COMP POOL strats

### ISSUE THREAD

**Issue by dougstorm** [yearn/yearn-strategies#25]
Description: MattDW Comp/ UNI pool strats

Commit: [f50a331772956cc9b2a6eaf9a6d27e5aa0859747](https://github.com/Mattdwest/poolTogether/commit/f50a331772956cc9b2a6eaf9a6d27e5aa0859747)

Latest Commit: [df873ac925d26b990a204dd2b3f7511e9192c12a]
(https://github.com/Mattdwest/poolTogether/commit/df873ac925d26b990a204dd2b3f7511e9192c12a)

Tag:

Scope: [faucet interface](https://github.com/Mattdwest/poolTogether/blob/master/interfaces/poolTogether/IPoolFaucet.sol)
[Pool interface](https://github.com/Mattdwest/poolTogether/blob/master/interfaces/poolTogether/IPoolTogether.sol)
[Generalized strategy for dai/usdc/comp/uni](https://github.com/Mattdwest/poolTogether/blob/master/contracts/StrategyPoolTogether.sol)

Repo: https://github.com/Mattdwest/poolTogether
[relevant contracts: ](https://docs.pooltogether.com/networks)

Deployed Contract TBD

Review Ongoing By:
- [x] Doug
- [x] Poolpi
- [x] Ryan

Review Completed By:
- [x] Doug
- [x] Poolpi
- [x] Ryan

NOTE: needs fixes on testing before going to PROD

**Comment by Mattdwest** [comment]
Description: MattDW Comp/ UNI pool strats

Commit: f50a331772956cc9b2a6eaf9a6d27e5aa0859747

Tag:

Scope: [faucet interface](https://github.com/Mattdwest/poolTogether/blob/master/interfaces/poolTogether/IPoolFaucet.sol)
[Pool interface](https://github.com/Mattdwest/poolTogether/blob/master/interfaces/poolTogether/IPoolTogether.sol)
[Generalized strategy for dai/usdc/comp/uni](https://github.com/Mattdwest/poolTogether/blob/master/contracts/StrategyDAIPoolTogether.sol)

Repo: Repo

Deployed Contract TBD

Review Ongoing By:

Review Completed By:

**Comment by TheRyanMiller** [comment]
@Mattdwest 

1. When `prepareMigration` is called, don't we want to add a `claimReward()` function call first so that we collect on all the POOL tokens before transferring the balance to the new strat?
2. Here you call `balanceOfWant()` on two consecutive lines. Can save some gas by setting return value to a variable.
https://github.com/Mattdwest/poolTogether/blob/8b11ab064a32436966182ae4dfde389a7794d6c6/contracts/StrategyDAIPoolTogether.sol#L274

**Comment by Mattdwest** [comment]
> @Mattdwest
> 
> 1. When `prepareMigration` is called, don't we want to add a `claimReward()` function call first so that we collect on all the POOL tokens before transferring the balance to the new strat?
> 2. Here you call `balanceOfWant()` on two consecutive lines. Can save some gas by setting return value to a variable.
>    https://github.com/Mattdwest/poolTogether/blob/8b11ab064a32436966182ae4dfde389a7794d6c6/contracts/StrategyDAIPoolTogether.sol#L274

#1) definitely doable. My logic was that we'd call harvest before a migration, so that they'd be empty.  I thought it would be safer to have migrate function do nothing more than just move the current holdings in case of an unforseen issue with the rewards contract in some way.

#2) Yep, excellent point. I can quickly edit this in here.

**Comment by poolpitako** [comment]
Finish my review, https://github.com/Mattdwest/poolTogether/pull/6 should be merged before re-deploying.

**Comment by Mattdwest** [comment]
Ok, I've combined a bunch of these fixes and merged and I think we're good to go.

**Comment by poolpitako** [comment]
Final review done! LGTM

**Comment by TheRyanMiller** [comment]
My review is complete - looks good!

**Comment by dougstorm** [comment]
looks like test are failing on the latest pushes
https://github.com/Mattdwest/poolTogether/runs/2089078012

@Mattdwest please update them to be sure the CI is green for the code and tests validations.

**Comment by dougstorm** [comment]
Suggestion (Not Critical):

Small optimization to avoid double reading balance here:
https://github.com/Mattdwest/poolTogether/blob/df873ac925d26b990a204dd2b3f7511e9192c12a/contracts/StrategyPoolTogether.sol#L291

```
 function liquidatePosition(uint256 _amountNeeded)
        internal
        override
        returns (uint256 _liquidatedAmount, uint256 _loss)
    {
        uint256 balanceOfWant = balanceOfWant();
        if (balanceOfWant < _amountNeeded) {
            // We need to withdraw to get back more want
            _withdrawSome(_amountNeeded.sub(balanceOfWant));
            // reload balance of want after side effect
            balanceOfWant = balanceOfWant();
        }

        if (balanceOfWant >= _amountNeeded) {
            _liquidatedAmount = _amountNeeded;
        } else {
            _liquidatedAmount = balanceOfWant;
            _loss = _amountNeeded.sub(balanceOfWant);
        }
    }
    ```

**Comment by dougstorm** [comment]
Suggestion (Not Critical):

Small optimization to avoid over reading balance in several places:
https://github.com/Mattdwest/poolTogether/blob/df873ac925d26b990a204dd2b3f7511e9192c12a/contracts/StrategyPoolTogether.sol#L262

```
function adjustPosition(uint256 _debtOutstanding) internal override {
        //emergency exit is dealt with in prepareReturn
        if (emergencyExit) {
            return;
        }
        
        uint256 balanceOfWant = balanceOfWant();

        // do not invest if we have more debt than want
        if (_debtOutstanding > balanceOfWant) {
            return;
        }

        // Invest the rest of the want
        uint256 _wantAvailable = balanceOfWant.sub(_debtOutstanding);
        if (_wantAvailable > 0) {
            IPoolTogether(wantPool).depositTo(
                address(this),
                _wantAvailable,
                ticket,
                refer
            );
        }
    }
    
    ```

**Comment by dougstorm** [comment]
Looks good overall, left a fix for the failing test and two minor gas optimizations that may save a bit of gas from current usage.

**Comment by Mattdwest** [comment]
> Looks good overall, requested fixes for the failing test and two minor gas optimizations that may save a bit of gas from current usage.

The newest version is https://github.com/Mattdwest/poolTogether/commit/e4479a326a1d539d5594129750e5434c703f2400.  Linting is busted (though I don't know how to fix that yet). 

The only difference between the above link and this one (https://github.com/Mattdwest/poolTogether/commit/cba05087363fc5e6b228943205a97f6971a01bdc) is the live migration tests.  This version has all tests passing and the fixes you requested.

**Comment by dougstorm** [comment]
looks good
