### ISSUE TITLE
IB Curve voterProxy strategy

### ISSUE THREAD

**Issue by dougstorm** [yearn/yearn-strategies#27]
Description: Iron Bank Curve Pool Strategy

Description: Iron Bank Curve Pool Strategy

Commit: [2183eba245f1760c5078ba9ad9e9370814e4ec8c](https://github.com/dudesahn/IB-Curve-Voter-Proxy/commit/2183eba245f1760c5078ba9ad9e9370814e4ec8c)

Latest Commit: [1dfccf6e7b6735cadbf05617077fc80fbb58ae8c](https://github.com/dudesahn/IB-Curve-Voter-Proxy/commit/1dfccf6e7b6735cadbf05617077fc80fbb58ae8c)

Repo: https://github.com/dudesahn/IB-Curve-Voter-Proxy

Scope: [StrategyCurveIBVoterProxy.sol](https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/master/contracts/StrategyCurveIBVoterProxy.sol)

Additional References or Repo (Link to underlying protocols or relevant documents)
-[sETH](https://github.com/matkam/yearn-strategies/blob/master/contracts/StrategyCurveEcrv.sol)

Deployed Contract TBD

Review Ongoing By:
- [x] Doug
- [x] Grandthrax
- [x] BAnteg

Review Completed By:
- [x] Doug
- [x] Grandthrax
- [x] BAnteg

**Comment by dudesahn** [comment]
**Updated to its own repo**

Description: Iron Bank Curve Pool Strategy

Commit: [2183eba245f1760c5078ba9ad9e9370814e4ec8c](https://github.com/dudesahn/IB-Curve-Voter-Proxy/commit/2183eba245f1760c5078ba9ad9e9370814e4ec8c)

Repo: https://github.com/dudesahn/IB-Curve-Voter-Proxy

Scope: [StrategyCurveIBVoterProxy.sol](https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/master/contracts/StrategyCurveIBVoterProxy.sol)

**Comment by dougstorm** [comment]
Suggestion:

Can remove this line since its not expected for strat to receive ETH

https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/199a87d1b8b09753e2749f1a13dc03c2f18a9698/contracts/StrategyCurveIBVoterProxy.sol#L262

**Comment by dougstorm** [comment]
Suggestion:

Use caps for constant for readibility `FEE_DENOMINATOR`

https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/199a87d1b8b09753e2749f1a13dc03c2f18a9698/contracts/StrategyCurveIBVoterProxy.sol#L31

**Comment by dougstorm** [comment]
Suggestion:

Remove unused code

https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/199a87d1b8b09753e2749f1a13dc03c2f18a9698/contracts/StrategyCurveIBVoterProxy.sol#L96

**Comment by dougstorm** [comment]
Fix:

Replace `path` as argument and instead pass the path as uint256 0,1,2 and use the already saved paths like an enum
0 = crvPathDai
1 = crvPathUsdc
2 = crvPathUsdt
else revert

avoids messing up the path by accident and also potential bad addresses in call data even if function is restricted it guarantees path is consistent for CRV in all cases.

https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/199a87d1b8b09753e2749f1a13dc03c2f18a9698/contracts/StrategyCurveIBVoterProxy.sol#L193

**Comment by dougstorm** [comment]
Suggestion:

Improve indentation for readability in `prepareReturn` for code blocks or run style in brownie mix

https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/199a87d1b8b09753e2749f1a13dc03c2f18a9698/contracts/StrategyCurveIBVoterProxy.sol#L122

**Comment by dougstorm** [comment]
Fix:

I think there is a possible bug here

https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/199a87d1b8b09753e2749f1a13dc03c2f18a9698/contracts/StrategyCurveIBVoterProxy.sol#L154

Should be
`CurveProxy.withdraw(crvIBgauge, address(want), Math.min(balanceOfStaked(), _debtOutstanding - _profit));`

Subtracting profits we have in hand from the withdraw amount?

I think on the reference strat that is the intention as well.

**Comment by dougstorm** [comment]
Optimization:

I think here after we `_sell` if we follow the advice of handling paths as enum of 0,1 and 2.

`_sell` can return the path used as a number

And we can save 400 gas minimum in checking here balances that we know are going to be 0

https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/199a87d1b8b09753e2749f1a13dc03c2f18a9698/contracts/StrategyCurveIBVoterProxy.sol#L143

later with the enum path number we can have function helpers to addLiquidity
```
if (pathUsed == 0) {
  uint256 daiBalance = Dai.balanceOf(address(this));
  crvIBpool.add_liquidity([daiBalance,0, 0], 0, true);
}
```

Depending on gas prices it may help out during harvest calls

**Comment by Grandthrax** [comment]
https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/master/contracts/StrategyCurveIBVoterProxyOnlyDai.sol#L63

Add want.balanceOf(address) here.

**Comment by Grandthrax** [comment]
You need to do proxy.lock() after you transfer keepCrv

**Comment by Grandthrax** [comment]
https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/master/contracts/StrategyCurveIBVoterProxyOnlyDai.sol#L105

Don't need this if statement any more

**Comment by Grandthrax** [comment]
https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/master/contracts/StrategyCurveIBVoterProxyOnlyDai.sol#L121

Remove sub(_profit)

**Comment by Grandthrax** [comment]
I prefer using a different method to migrate incase the reason we migrate is a problem in perpareReturn. See here for example:
https://github.com/Grandthrax/yearnv2_steth_crv_strat/blob/master/contracts/Strategy.sol#L241

**Comment by Grandthrax** [comment]
https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/master/contracts/StrategyCurveIBVoterProxyOnlyDai.sol#L158

I dont think this is relevant? I don't think you hold any crvIBgauge tokens

**Comment by dudesahn** [comment]
@dougstorm and @Grandthrax; I think I rectified most of your issues here: 

https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/master/contracts/StrategyCurveIBVoterProxyOptions.sol

@dougstorm I'm still trying to figure out the best way to do what you suggested below; if you could check out what I have so far and let me know ways that I can tweak it that would be great. I will also spend more time looking/thinking about this tomorrow.

> Fix:
> 
> Replace `path` as argument and instead pass the path as uint256 0,1,2 and use the already saved paths like an enum
> 0 = crvPathDai
> 1 = crvPathUsdc
> 2 = crvPathUsdt
> else revert
> 
> avoids messing up the path by accident and also potential bad addresses in call data even if function is restricted it guarantees path is consistent for CRV in all cases.
> 
> https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/199a87d1b8b09753e2749f1a13dc03c2f18a9698/contracts/StrategyCurveIBVoterProxy.sol#L193

**Comment by dudesahn** [comment]
Think I've got it finalized now. Gas costs are: 


  | Average Harvest Gas | Gas @ 150 gwei | ETH Price | Cost
-- | -- | -- | -- | --
Original | 1,357,844 | 0.00000015 | $1,356.07 | $276.20
DAI-Only | 931,784 | 0.00000015 | $1,356.07 | $189.53
Options | 1,142,722 | 0.00000015 | $1,356.07 | $232.44

So, new version is definitely more efficient than original version, but not as efficient as the version where we go straight with DAI only. Would love if there are any more optimizations you can suggest that I can make; thanks!

**Comment by dougstorm** [comment]
Suggestion:

Small style check:
https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/fb92595cd59eaada21929eef8473694b929f9f67/contracts/StrategyCurveIBVoterProxy.sol#L110

**Comment by dougstorm** [comment]
All comment changes where implemented, IMO optimization is not a showstopper over functionality

**Comment by dudesahn** [comment]
@dougstorm, attached is the link to my most recent commit (should be final, now): [71cff2319f8d813fde797fcfebf0ef6902f6a746](https://github.com/dudesahn/IB-Curve-Voter-Proxy/commit/71cff2319f8d813fde797fcfebf0ef6902f6a746#diff-fa23ecea347bacb9eb40a9b09cc33e9d99d922eba853189b69fd18933c9d38e5)

**Comment by dougstorm** [comment]
Suggestion:

Remove this block of code of approvals not needed?

https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/798d725b2ffbe3dc4ee44966ced3a51a27e838f3/contracts/StrategyCurveIBVoterProxy.sol#L206

**Comment by dougstorm** [comment]
Suggestion:

For readability you can add constants to be sure what 0 and 1 means  at the top for each option

```
uint256 public constant CHECK_LIQ_GUAGE_TRUE = 1;
uint256 public constant CHECK_LIQ_GUAGE_FALSE = 0;
```
And reference them instead of the magic numbers here:
https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/798d725b2ffbe3dc4ee44966ced3a51a27e838f3/contracts/StrategyCurveIBVoterProxy.sol#L198

**Comment by dougstorm** [comment]
Suggestion:
Can remove the else here using a constant 

```
// 1 is for TRUE value and 0 for FALSE to keep in sync with binary convention
  if (_isSushiswap == USE_SUSHISWAP) {
            address sushiswapRouter =
                0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F; // default to sushiswap
            crvRouter = sushiswapRouter;
        } else {
            address uniswapRouter = 0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D;
            crvRouter = uniswapRouter;
        } 
```



https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/798d725b2ffbe3dc4ee44966ced3a51a27e838f3/contracts/StrategyCurveIBVoterProxy.sol#L217

**Comment by dudesahn** [comment]
https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/master/contracts/StrategyCurveIBVoterProxy.sol

**Comment by dougstorm** [comment]
All changes look good to me

**Comment by Grandthrax** [comment]
looks good to me

**Comment by banteg** [comment]
1. CRV approval will fail when you switch an exhange
https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/64e0dc96f1411b4880a6f077b5621702faeb2e88/contracts/StrategyCurveIBVoterProxy.sol#L201
The reason for it is that CRV token [requires](https://github.com/curvefi/curve-contract/blob/80bbe179083c9a7062e4c482b0be3bfb7501f2bd/contracts/tokens/CurveTokenV1.vy#L117) resetting approval to 0 before adjusting the value
2. Rename `curveProxy` to `proxy` to keep it consistent with other strategies. For example, yearn-exporter [depends](https://github.com/yearn/yearn-exporter/blob/7c23c06d59a6d90956a5adab5ef93e18ae16483f/yearn/vaults_v1.py#L60) on this naming.
3. `.add(1800)` is redundant here, you can as well use `now`
https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/64e0dc96f1411b4880a6f077b5621702faeb2e88/contracts/StrategyCurveIBVoterProxy.sol#L147
4. Why not select optimal path automatically?

**Comment by poolpitako** [comment]
reviewed! LGTM

**Comment by dudesahn** [comment]
Deployed Vault: https://etherscan.io/address/0x27b7b1ad7288079a66d12350c828d3c00a6f07d7

Deployed Strategy: https://etherscan.io/address/0x5c0309fa022Bc1B73fE45A2D73EddeD58a820ff8

Currently awaiting approval of my strategy on proxy, but operation, revoke, and migration tests all passed with live contracts on mainnet fork.

**Comment by dudesahn** [comment]
Newest commit with updates to the tend/harvest flow, including updates to tendTrigger, harvestTrigger, prepareReturn, and adjustPosition: [9d33a9c7ea86150054ce13fd78b00d190bc13904](https://github.com/dudesahn/IB-Curve-Voter-Proxy/commit/9d33a9c7ea86150054ce13fd78b00d190bc13904).

Idea here is to conduct more frequent tends, as they are cheaper gas-wise and will give us the same savings on slippage but without the extra gas cost of a harvest. Then, for optimal compounding, we adjust our harvest frequency so that we harvest every x tends.

**Comment by dudesahn** [comment]
@dougstorm updated all tests; everything passing now.

**Comment by dougstorm** [comment]
Latest updates look good to me, also test are passing on my local
![Uploading Screen Shot 2021-03-20 at 09.35.58.png…]()
