### ISSUE TITLE
wETHv2 single sided strat for ETH Orbxball

### ISSUE THREAD

**Issue by dougstorm** [yearn/yearn-strategies#31]
Description: single sided ETH strat with Curve

Commit: [??](??)

Repo: https://github.com/orbxball/single-sided-weth

Scope: [Strategy.sol](https://github.com/orbxball/single-sided-weth/blob/master/contracts/Strategy.sol)

Additional References or Repo (Link to underlying protocols or relevant documents)
-link to curve ETH strats?

Deployed Contract TBD

Review Ongoing By:
- [x] Doug
- [x] Grandthrax

Review Completed By:
- [x] Doug
- [x] Grandthrax

**Comment by Grandthrax** [comment]
https://github.com/orbxball/single-sided-weth/blob/master/contracts/Strategy.sol#L126

I think it would be better to combine with line 136. So that you only do one withdrawal. Each withdrawal could be really expensive so best to keep as minimal as possible.

**Comment by Grandthrax** [comment]
https://github.com/orbxball/single-sided-weth/blob/master/contracts/Strategy.sol#L198

I don't think you need after sub before. Because there should be no ETH there and any that is will be trapped. Just deposit full balance.

**Comment by Grandthrax** [comment]
https://github.com/orbxball/single-sided-weth/blob/master/contracts/Strategy.sol#L176

Do a _liquidatedAmount = Math.min(_liquidatedAmount , _amountNeeded)

There are vault reverts if returning more than asked for.

**Comment by Grandthrax** [comment]
https://github.com/orbxball/single-sided-weth/blob/master/contracts/Strategy.sol#L154

Here you will get a revert if slippage is too high which will revert all of harvest. Effectively locking the strategy until manual intervention. I prefer to do a graceful exit. See here:

https://github.com/Grandthrax/SingleSidedCurve/blob/master/contracts/Strategy.sol#L191

I have a function that checks the slippage so that I can just not deposit when it would revert. It is more expensive on gas but it means that we can still harvest normally when pool is off peg.

**Comment by orbxball** [comment]
> https://github.com/orbxball/single-sided-weth/blob/master/contracts/Strategy.sol#L126
> 
> I think it would be better to combine with line 136. So that you only do one withdrawal. Each withdrawal could be really expensive so best to keep as minimal as possible.

done it to save gas with a new accounting method.

**Comment by orbxball** [comment]
> https://github.com/orbxball/single-sided-weth/blob/master/contracts/Strategy.sol#L198
> 
> I don't think you need after sub before. Because there should be no ETH there and any that is will be trapped. Just deposit full balance.

it's to avoid withdrawing more if there's any trapped eth. won't cost too much on this. instead, I changed to put trapped eth into full deposit. that makes more sense.

**Comment by orbxball** [comment]
> https://github.com/orbxball/single-sided-weth/blob/master/contracts/Strategy.sol#L176
> 
> Do a _liquidatedAmount = Math.min(_liquidatedAmount , _amountNeeded)
> 
> There are vault reverts if returning more than asked for.

nice check! done.

**Comment by orbxball** [comment]
> https://github.com/orbxball/single-sided-weth/blob/master/contracts/Strategy.sol#L154
> 
> Here you will get a revert if slippage is too high which will revert all of harvest. Effectively locking the strategy until manual intervention. I prefer to do a graceful exit. See here:
> 
> https://github.com/Grandthrax/SingleSidedCurve/blob/master/contracts/Strategy.sol#L191
> 
> I have a function that checks the slippage so that I can just not deposit when it would revert. It is more expensive on gas but it means that we can still harvest normally when pool is off peg.

this is a good point. trade-off between gas usage and revert. in this case, eth is usually the less amount side, then gas usage could be prioritized. but I will keep track on the pool state to see if there's a migration needed.

**Comment by dougstorm** [comment]
Strat Looks good to me  with latest commits
