### ISSUE TITLE
crvREN BTC Badger orbxball

### ISSUE THREAD

**Issue by dougstorm** [yearn/yearn-strategies#35]
Description: curve ren BTC badger

Commit: [011a492154199d2dc6517b27de0e0d9551b0b820](https://github.com/orbxball/crvrenbtc-badger/commit/011a492154199d2dc6517b27de0e0d9551b0b820)

Repo: https://github.com/orbxball/crvrenbtc-badger

Scope: [Strategy.sol](https://github.com/orbxball/crvrenbtc-badger/blob/master/contracts/Strategy.sol)

Additional References or Repo (Link to underlying protocols or relevant documents)
-
Deployed Contract TBD

Review Ongoing By:
- [x] Doug
- [x] Grandthrax

Review Completed By:
- [x] Doug
- [x] Grandthrax

**Comment by dougstorm** [comment]
Looks good, diff review against other voter Proxy strats in v1. Needs gauge to be removed from v1 before enabling this one

**Comment by Grandthrax** [comment]
Remember to set profitFactor  and debtThreshold. they are important for keepers. I recommend about 1500 for profitFactor  and equivalent of $2m for debtThreshold

**Comment by Grandthrax** [comment]
Apart from that all looks good
