### ISSUE TITLE
Fixes to USDT, USDC and TUSD strategy

### ISSUE THREAD

**Issue by fameal** [yearn/yearn-strategies#37]
**Description**: 
I've fixed definitely the profit issue (1 wei was going back and forth) and fixed Sam comment. 

I also did the followings:

1. improved test coverage (i.e. setters, migration, operations)
2. added support for management (from vault) for specific settings leaving the delicate ones to governance only
3. improved approximation management with configurable parameters
4. optimized gas consumption for cheaper harvest and withdrawal (no more safe approve everytime)

This is for 0.3.1 as soon as we merge it I will propagate the changes to 0.3.2. So then we can deploy the new WBTC but ultimately USDT!

**Commit (hash)**: 

**Tag**:

**Repo**: https://github.com/emilianobonassi/yIdleStrategies

**Scope**: (List link to files)
- https://github.com/emilianobonassi/yIdleStrategies/pull/6

**Additional References or Repo** (Link to underlying protocols or relevant documents):

**Deployed Contract** (etherscan link): 

**Review Ongoing By**:
- [x] Sam
- [x] Doug

**Review Completed By**:
- [x] Sam
- [x] Doug

**Comment by dougstorm** [comment]
Minor Suggestion;

How many governance tokens are there going to be to handle? 3 or 4? should we cap it here? don't think it will be able to handle a big number and will run out of gas on some operations that are key.

https://github.com/emilianobonassi/yIdleStrategies/blob/5f1ecda27f523bd2abb2a8d012f5a0c18a8c44b8/contracts/StrategyIdle.sol#L138

**Comment by emilianobonassi** [comment]
@dougstorm done

https://github.com/emilianobonassi/yIdleStrategies/commit/3be7c117b4e76ce1e98f370b90b17f0bcc1d9af2

**Comment by dougstorm** [comment]
all changes look good to deploy

**Comment by dougstorm** [comment]
https://github.com/emilianobonassi/yIdleStrategies/commit/2b65bc129df2cfdb9a297b257cad7e9444c05fc1

Changes from latest commit look good
