### ISSUE TITLE
masterchef gen strat

### ISSUE THREAD

**Issue by dougstorm** [yearn/yearn-strategies#39]
**Description**: YFI BDP masterchef strat
**Commit (hash)**: 

**Tag**:

**Repo**: https://github.com/Grandthrax/yearnv2-masterchef-generic/

Repo: 
**Scope**: (List link to files)
- https://github.com/Grandthrax/yearnv2-masterchef-generic/blob/master/contracts/Strategy.sol

**Additional References or Repo** (Link to underlying protocols or relevant documents):

**Deployed Contract** (etherscan link): 
Strategy : ??
Vault : ??

**Review Ongoing By**:
- [X] Doug
- [X] Poolpi

**Review Completed By**:
- [X] Doug
- [X] Poolpi

**Comment by dougstorm** [comment]
Suggestion:

Router can be passes as bool in similar pattern `useSushi = true`

https://github.com/Grandthrax/yearnv2-masterchef-generic/blob/725b2de06e48f07780b38a681ef100d6f126fdfe/contracts/Strategy.sol#L99

**Comment by dougstorm** [comment]
Suggestion:

Stick with existing routers as option with a bool only

https://github.com/Grandthrax/yearnv2-masterchef-generic/blob/725b2de06e48f07780b38a681ef100d6f126fdfe/contracts/Strategy.sol#L182

**Comment by Grandthrax** [comment]
https://github.com/Grandthrax/yearnv2-masterchef-generic/commit/cbb15b676821caad159fdd2a8faae63b9a75dc2b
