### ISSUE TITLE
yveCRV Auto-compounding Strategy

### ISSUE THREAD

**Issue by TheRyanMiller** [yearn/yearn-strategies#41]
**Description**: This strategy takes yveCRV, claims weekly 3Crv rewards and uses them to either market-buy or mint new yveCRV based on which is more efficient.

**Commit (hash)**: dda194028865922200103b24cd4c4456521567ca

**Tag**: Master

**Repo**: https://github.com/andy8052/yveCRV-vault

**Scope**: (List link to files)
- [Strategy.sol](https://github.com/andy8052/yveCRV-vault/blob/master/contracts/Strategy.sol)

**Additional References or Repo** (Link to underlying protocols or relevant documents):
n/a  

**Deployed Contract** (etherscan link): 

**Review Ongoing By**:
- [x] Banteg 
- [x] Andy
- [x] Doug

**Review Completed By**:
- [x] Banteg
- [x] Andy
- [x] Doug

NOTE: and audited was completed on this strategy as well as the reviews

**Comment by banteg** [comment]
1. `claimable` is only updated on interactions, it'll be 0 most of the time, which breaks the logic in several places which expect non zero value. The correct claimable amount would be `(index - supplyIndex) * balanceOf(addr) / 1e18 + claimable`
https://github.com/andy8052/yveCRV-vault/blob/599222bcbb4a64decb162c233f0d4efbf3e762bc/contracts/Strategy.sol#L101
https://github.com/andy8052/yveCRV-vault/blob/599222bcbb4a64decb162c233f0d4efbf3e762bc/contracts/Strategy.sol#L129
2. `ADD_PRECISION` is unused, also, I don't really see value in golfing `getAmountsOut`
https://github.com/andy8052/yveCRV-vault/blob/599222bcbb4a64decb162c233f0d4efbf3e762bc/contracts/Strategy.sol#L177
2. As a fun `adjustPosition` we can add arbitrage of yveCRV > CRV price.

**Comment by TheRyanMiller** [comment]
> 1. (index - supplyIndex) * balanceOf(addr) / 1e18 + claimable
OK, I think I understand, please let me know if I'm correct here:
- Current implementation of `claimable` is incorrect because this value only updates on interactions. In most cases this shows 0, but in reality, the address actually may have more.
- To get the additional value, we calculate `(index - supplyIndex) * balanceOf(addr)`

How does this look? Here I put claimable in terms of `1e18`, rather than dividing `claimableToAdd` by 1e18.
![image](https://user-images.githubusercontent.com/3812035/110649802-f4a5b280-8187-11eb-83f1-a501819402d1.png)

**Comment by dougstorm** [comment]
suggestion:

can use baseStrategy modifiers `onlyGovernance`

https://github.com/andy8052/yveCRV-vault/blob/3fe741cf0fcc44ce97cd4ec9a952595753ebd530/contracts/Strategy.sol#L259

**Comment by dougstorm** [comment]
Removal:

Governance should come from vault always, should not be set by strategy outside vault governance

https://github.com/andy8052/yveCRV-vault/blob/3fe741cf0fcc44ce97cd4ec9a952595753ebd530/contracts/Strategy.sol#L263

**Comment by dougstorm** [comment]
Suggestion:

is there a ceiling value we need to cap here?

https://github.com/andy8052/yveCRV-vault/blob/3fe741cf0fcc44ce97cd4ec9a952595753ebd530/contracts/Strategy.sol#L258

**Comment by dougstorm** [comment]
Small Optimization from Banteg's comment if it can be zero:

https://github.com/andy8052/yveCRV-vault/blob/3fe741cf0fcc44ce97cd4ec9a952595753ebd530/contracts/Strategy.sol#L228

```
function getClaimable3Crv() public view returns (uint256 _claimable) {
        IyveCRV YveCrv = IyveCRV(address(want));
        uint256 _claimable = YveCrv.claimable(address(this));
        if (_claimable > 0) {
           uint256 claimableToAdd = (YveCrv.index() - YveCrv.supplyIndex(address(this)))
                .mul(YveCrv.balanceOf(address(this)))
                .div(1e18);
            _claimable =  _claimable.mul(1e18).add(claimableToAdd);
       }
        
    }
    ```

**Comment by dougstorm** [comment]
Possible Small Optimization:

https://github.com/andy8052/yveCRV-vault/blob/3fe741cf0fcc44ce97cd4ec9a952595753ebd530/contracts/Strategy.sol#L106

```
function estimatedTotalAssets() public view override returns (uint256 _totalAssets) {
        uint256 _totalAssets = want.balanceOf(address(this));
        uint256 claimable = getClaimable3Crv();        
        if(claimable > 0){
            uint256 stable = 0;
            stable = quoteWithdrawFromCrv(claimable); // Calculate withdrawal amount
            uint256 estveCrv = 0;
            if(stable > 0){ // Quote will revert if amount is < 1
                estveCrv = quote(usdc, address(want), stable);
                // only here do we mutate total assets if all conditions are correct
                 _totalAssets =  _totalAssets.add(estveCrv);
            }
            
        }
        
    }
```

**Comment by TheRyanMiller** [comment]
Thanks @dougstorm. 

- Governance + ceiling suggestions are now implemented.
- Your first optimization suggestion cannot be done because most common case is `claimable == 0`, while `claimableToAdd > 0`.
- Second optimization/readability suggestion is very good. It is now implemented.

**Comment by dougstorm** [comment]
closing since audit is completed
