### ISSUE TITLE
weth v2 maker strat

### ISSUE THREAD

**Issue by dougstorm** [yearn/yearn-strategies#42]
Description: WETH v2 maker strat

Commit: [da1ced169806977545b6745991fdaf6ef51dde83](https://github.com/orbxball/weth-maker/commit/da1ced169806977545b6745991fdaf6ef51dde83)

Tag:

Scope: [Strategy](https://github.com/orbxball/weth-maker/blob/master/contracts/Strategy.sol)

Repo: https://github.com/orbxball/weth-maker

[relevant contracts: ]
Reference implementation from v1:
https://github.com/yearn/yearn-protocol/blob/develop/contracts/strategies/StrategyMKRVaultDAIDelegate.sol
Deployed Contract TBD

Review Ongoing By:
- [x] Doug
- [x] BAnteg

Review Completed By:
- [x] Doug
- [x] BAnteg

**Comment by dougstorm** [comment]
Question:

Do we need to check here how much dai we have already in balance before withdrawing the complete requested amount in liquidate?
https://github.com/orbxball/weth-maker/blob/da1ced169806977545b6745991fdaf6ef51dde83/contracts/Strategy.sol#L272

**Comment by dougstorm** [comment]
Question:

does this need to be public/external?

**Comment by dougstorm** [comment]
Suggestion:

remove if not used?

https://github.com/orbxball/weth-maker/blob/da1ced169806977545b6745991fdaf6ef51dde83/contracts/Strategy.sol#L313

**Comment by dougstorm** [comment]
Reviewed and left two comments so far

**Comment by Grandthrax** [comment]
https://github.com/orbxball/weth-maker/blob/master/contracts/Strategy.sol#L276

This line will be wrong if the pervious if statement comes back false

**Comment by Grandthrax** [comment]
https://github.com/orbxball/weth-maker/blob/master/contracts/Strategy.sol#L158

Doesn't this happen in deposit()?

**Comment by Grandthrax** [comment]
https://github.com/orbxball/weth-maker/blob/master/contracts/Strategy.sol#L301

Will this be too sensitive and trigger every time there is a small move in price? maybe consider adding a threshold before which tend is called

**Comment by Grandthrax** [comment]
https://github.com/orbxball/weth-maker/blob/master/tests/test_migration.py#L6

I would like to see a migration test to show that there is an escape in worse case scenario

**Comment by Grandthrax** [comment]
https://github.com/orbxball/weth-maker/blob/master/tests/test_operation.py#L34
I suggest adding in a delay and then a harvest on some of the underlying strategies on the dai vault. To confirm that profit is being recorded properly and withdrawal works after there is a profit

**Comment by poolpitako** [comment]
> https://github.com/orbxball/weth-maker/blob/master/contracts/Strategy.sol#L301
> 
> Will this be too sensitive and trigger every time there is a small move in price? maybe consider adding a threshold before which tend is called

yep, I came to say that. I would make the `tendTrigger` return true only when we need to repay. Not always.

**Comment by poolpitako** [comment]
https://github.com/orbxball/weth-maker/blob/master/contracts/Strategy.sol#L394
Can be:
```
Uni(dex).swapExactTokensForTokens(_amountIn, 0, path, address(this), now);
```

**Comment by poolpitako** [comment]
Please, add more tests, I would like to see:
 - revoking strategy with profit
 - migrate strategy
 - changing the debt ratio up and down

**Comment by orbxball** [comment]
> Question:
> 
> Do we need to check here how much dai we have already in balance before withdrawing the complete requested amount in liquidate?
> https://github.com/orbxball/weth-maker/blob/da1ced169806977545b6745991fdaf6ef51dde83/contracts/Strategy.sol#L272

I checked with the return value of `_withdrawDai` but decided to remove it eventually. 
repaying more wont create an issue. but it's possible that `_withdrawDai` might return less than expected, so using all balance makes the maker vault safer.

**Comment by orbxball** [comment]
> Suggestion:
> 
> remove if not used?
> 
> https://github.com/orbxball/weth-maker/blob/da1ced169806977545b6745991fdaf6ef51dde83/contracts/Strategy.sol#L313

it's used externally with `onlyAuthorized` while handling maker vault.

**Comment by orbxball** [comment]
> Question:
> 
> does this need to be public/external?
> 
> https://github.com/orbxball/weth-maker/blob/da1ced169806977545b6745991fdaf6ef51dde83/contracts/Strategy.sol#L309

yes. it's kept `onlyAuthorized` if manual operation on maker vault is needed.

**Comment by orbxball** [comment]
> Suggestion:
> 
> remove if not used?
> 
> https://github.com/orbxball/weth-maker/blob/da1ced169806977545b6745991fdaf6ef51dde83/contracts/Strategy.sol#L313

for authorized external use

**Comment by orbxball** [comment]
> https://github.com/orbxball/weth-maker/blob/master/contracts/Strategy.sol#L276
> 
> This line will be wrong if the pervious if statement comes back false

- `_amountNeeded` is denominated in weth, and all weth are locked in the maker vault, so it's guaranteed that all requested amount can be taken out. (as long as the vault doesnt mess up debt management)

- if the if statement come back false, it means that there's enough weth in the maker vault that could be taken out w/o taking the underlying dai. otherwise, the if is true and then it withdraws some dai before taking weth out to make sure the maker vault is within a safe c-ratio.

**Comment by orbxball** [comment]
> https://github.com/orbxball/weth-maker/blob/master/contracts/Strategy.sol#L158
> 
> Doesn't this happen in deposit()?

usually yes. but there's an edge case that `_deposit()` more weth is decoupled from the direct `draw()` on the maker vault.

**Comment by orbxball** [comment]
> https://github.com/orbxball/weth-maker/blob/master/contracts/Strategy.sol#L301
> 
> Will this be too sensitive and trigger every time there is a small move in price? maybe consider adding a threshold before which tend is called

no. currently there's a 5% changable buffer. so let's say the default c-ratio is 200%, and the trigger will be trigged when it's below 195% or above 205%. and then it decides if it's the case to draw more or repay debt.

**Comment by orbxball** [comment]
> > https://github.com/orbxball/weth-maker/blob/master/contracts/Strategy.sol#L301
> > Will this be too sensitive and trigger every time there is a small move in price? maybe consider adding a threshold before which tend is called
> 
> yep, I came to say that. I would make the `tendTrigger` return true only when we need to repay. Not when we have want to deposit.

the original design was only repay. banteg and andre wanted more capital efficiency so draw were included. 
but I agree, repayment is emergent, whereas capital efficiency is good-to-have. this part can be optimized with `callCost`.

**Comment by orbxball** [comment]
> Please, add more tests, I would like to see:
> 
> * revoking strategy with profit
> * migrate strategy
> * changing the debt ratio up and down

done

**Comment by dougstorm** [comment]
latest changes look good, left only a comment above

**Comment by orbxball** [comment]
> > > Question:
> > > does this need to be public/external?
> > > https://github.com/orbxball/weth-maker/blob/da1ced169806977545b6745991fdaf6ef51dde83/contracts/Strategy.sol#L309
> > 
> > 
> > yes. it's kept `onlyAuthorized` if manual operation on maker vault is needed.
> 
> ok if its needed, are there concerns with strategist being able to send any `dst` address?
> or should we change modifier to `onlyGovernance`, thinking if this becomes a widely used template
> also removing strategist from single point of failure

economically no. it only allows `dst` to manage debt. but agree with your statement. took it.
one note is that the trade-off of `onlyGovernance` is slower reaction. when there's a need of manual operation on maker vault, gov might need to react more quickly.
