### ISSUE TITLE
Maker v2 YFI Strat

### ISSUE THREAD

**Issue by dougstorm** [yearn/yearn-strategies#43]
Description: YFI v2 maker strat

Commit: [667feef808354bc671fe8d45d65901d8c14898f5](https://github.com/orbxball/yfi-maker/commit/667feef808354bc671fe8d45d65901d8c14898f5)

Tag:

Scope: 
[Strategy](https://github.com/orbxball/yfi-maker/blob/master/contracts/Strategy.sol)
[OSMedianizer](https://github.com/orbxball/yfi-maker/blob/master/contracts/OSMedianizer.sol)

Repo: https://github.com/orbxball/yfi-maker

[relevant contracts: ]
Reference implementation from v1:
https://github.com/yearn/yearn-protocol/blob/develop/contracts/strategies/StrategyMKRVaultDAIDelegate.sol
Deployed Contract TBD

Review Ongoing By:
- [x] Doug
- [x] Grandthrax
- [x] banteg

Review Completed By:
- [x] Doug
- [x] Grandthrax
- [x] banteg

**Comment by dougstorm** [comment]
Suggestion:

Leaning same comment as in weth maker strat

https://github.com/yearn/yearn-strategies/issues/42#issuecomment-797658941

**Comment by banteg** [comment]
- [ ] Allow oracle adapter in our whitelisted oracle proxy to enable `peep()`
`0x208EfCD7aad0b5DD49438E0b6A0f38E951A50E5f.set_user(0x2953554810F73aD0498F6C948FB6eedf15747EE0, True)`

**Comment by dougstorm** [comment]
strategy is live
