### ISSUE TITLE
Generic Synthetix Rewards strategy

### ISSUE THREAD

**Issue by akshaynexus** [yearn/yearn-strategies#48]
**Description**: This strategy is a generic contract which is suited for synthetix based reward contracts.On harvests the strategy sells the rewards for more want.Code is based off of the masterchef generic contract but redone to support synthetix rewards based contracts.
Current tests are testing the currently uninitalized yfi staking pool for bank rewards

**Commit (hash)**:  5b891828b6e16192d9b2984d02b223b947f2f8e1

**Tag**: master

**Repo**: https://github.com/akshaynexus/yearnv2-synthetixrewards-generic

**Scope**: (List link to files)
- https://github.com/akshaynexus/yearnv2-synthetixrewards-generic/blob/master/contracts/Strategy.sol

**Additional References or Repo** (Link to underlying protocols or relevant documents):
- https://github.com/Grandthrax/yearnv2-masterchef-generic
- https://github.com/Synthetixio/synthetix/blob/develop/contracts/StakingRewards.sol (for standard Synthetix staking rewards reference)

Using this staker contract: https://etherscan.io/address/0x90d1d83fd4cca873848d728fd8cef382b1acb4b8#code

**Deployed Contract** (etherscan link): 

**Review Ongoing By**:
- [x] Poolpi
- [x] Grandthrax
- [x] Doug

**Review Completed By**:
- [x] Poolpi
- [x] Grandthrax
- [x] Doug

NOTE: experimental strat needs some data backing to be collected

**Comment by poolpitako** [comment]
https://github.com/akshaynexus/yearnv2-synthetixrewards-generic/blob/master/contracts/Strategy.sol#L36
Move this initialization to `_initializeStrat`

**Comment by poolpitako** [comment]
Plz kill https://github.com/akshaynexus/yearnv2-synthetixrewards-generic/blob/master/contracts/Strategy.sol#L94
let's leave a single clone method.

**Comment by poolpitako** [comment]
why https://github.com/akshaynexus/yearnv2-synthetixrewards-generic/blob/master/contracts/Strategy.sol#L202 instead of making the variable public?

**Comment by poolpitako** [comment]
I would remove this logic, https://github.com/akshaynexus/yearnv2-synthetixrewards-generic/blob/master/contracts/Strategy.sol#L84
Caller should know exactly what's the reward.

**Comment by akshaynexus** [comment]
Ok will remove the extra additions for getting the reward and stake token from the staking contract

**Comment by akshaynexus** [comment]
> why https://github.com/akshaynexus/yearnv2-synthetixrewards-generic/blob/master/contracts/Strategy.sol#L202 instead of making the variable public?

This is so that one can see what the path is on etherscan for example,although probably was a unnecessary change

**Comment by poolpitako** [comment]
Might be useful for others: diff between @Grandthrax and @akshaynexus code
https://github.com/Grandthrax/yearnv2-masterchef-generic/compare/master...akshaynexus:master

**Comment by poolpitako** [comment]
Please, fix or remove commented code at: https://github.com/akshaynexus/yearnv2-synthetixrewards-generic/blob/master/tests/test_live.py#L1

**Comment by poolpitako** [comment]
Rest looks good 👍

**Comment by akshaynexus** [comment]
> Please, fix or remove commented code at: https://github.com/akshaynexus/yearnv2-synthetixrewards-generic/blob/master/tests/test_live.py#L1

Fixed

**Comment by akshaynexus** [comment]
> I would remove this logic, https://github.com/akshaynexus/yearnv2-synthetixrewards-generic/blob/master/contracts/Strategy.sol#L84
> Caller should know exactly what's the reward.
Fixed

**Comment by akshaynexus** [comment]
> Plz kill https://github.com/akshaynexus/yearnv2-synthetixrewards-generic/blob/master/contracts/Strategy.sol#L94
> let's leave a single clone method.

Fixed

**Comment by Grandthrax** [comment]
@dougstorm here is comparison with MasterChef which you have already reviewed: 

https://github.com/Grandthrax/yearnv2-masterchef-generic/compare/master...akshaynexus:master

A nice addition of if(!emergencyExit) in liquidatePosition

**Comment by dougstorm** [comment]
Comment:

This error message should be changed?
https://github.com/akshaynexus/yearnv2-synthetixrewards-generic/blob/e53504640bc2cb84d6d24a0e602c8eee717ae1ed/contracts/Strategy.sol#L74

**Comment by dougstorm** [comment]
Comment:

Would it make sense to change these two modifiers to `onlyKeepers`  instead of governance for fast reaction? Is there any downside?

https://github.com/akshaynexus/yearnv2-synthetixrewards-generic/blob/e53504640bc2cb84d6d24a0e602c8eee717ae1ed/contracts/Strategy.sol#L298

https://github.com/akshaynexus/yearnv2-synthetixrewards-generic/blob/e53504640bc2cb84d6d24a0e602c8eee717ae1ed/contracts/Strategy.sol#L302

**Comment by dougstorm** [comment]
Fixed needed:

Test are failing with a conftest issue it seems

```
def strategy(strategist, keeper, vault, Strategy, gov, yfibank, bank, router):
>       strategy = strategist.deploy(Strategy, vault, yfibank, router, yfi, bank)
E       ValueError: constructor '<function yfi at 0x108d9ec10>' - '<function yfi at 0x108d9ec10>' is not a valid ETH address
```

**Comment by akshaynexus** [comment]
> Fix needed:
> 
> Test are failing with a conftest issue it seems
> 
> ```
> def strategy(strategist, keeper, vault, Strategy, gov, yfibank, bank, router):
> >       strategy = strategist.deploy(Strategy, vault, yfibank, router, yfi, bank)
> E       ValueError: constructor '<function yfi at 0x108d9ec10>' - '<function yfi at 0x108d9ec10>' is not a valid ETH address
> ```

should be fixed now

**Comment by Grandthrax** [comment]
approved by me

**Comment by dougstorm** [comment]
Suggestion:

This is not an issue for this deployed contract.

but could be good to reset the infinite approval here to zero:

https://github.com/akshaynexus/yearnv2-synthetixrewards-generic/blob/b9d3afd14ca4446a7e1d7620864a25b858bf2fd3/contracts/Strategy.sol#L102

as a safety measure in case other staker contracts are hijacked or upgraded under our watch

`enableApproval() onlyGuardians`
`disableApproval() onlyGuardians`

**Comment by akshaynexus** [comment]
> Suggestion:
> 
> This is not an issue for this deployed contract.
> 
> but could be good to reset the infinite approval here to zero:
> 
> https://github.com/akshaynexus/yearnv2-synthetixrewards-generic/blob/b9d3afd14ca4446a7e1d7620864a25b858bf2fd3/contracts/Strategy.sol#L102
> 
> as a safety measure in case other staker contracts are hijacked or upgraded under our watch
> 
> `enableApproval() onlyGuardians`
> `disableApproval() onlyGuardians`

added now

**Comment by dougstorm** [comment]
Looks good to go
