### ISSUE TITLE
Generic Single Sided Curve Targeting IBCrv

### ISSUE THREAD

**Issue by Grandthrax** [yearn/yearn-strategies#53]
**Description**:  Single sided curve strat. Previously reviewed but extended to include cloning

**Commit (hash)**:  https://github.com/Grandthrax/SingleSidedCurve/commit/b20a65514e1beb93ce871d2fb6bd06682ea1d03b

**Tag**: v2/030

**Repo**: https://github.com/Grandthrax/SingleSidedCurve/tree/v2/030

**Scope**: (List link to files)
- Strategy.sol

**Review Ongoing By**:
- [x] Doug
- [x] Poolpi

**Review Completed By**:
- [x] Doug
- [x] Poolpi

Reference original review:
https://github.com/Grandthrax/SingleSidedCurve/issues/1

**Comment by Grandthrax** [comment]
Poolpi review fixes:
https://github.com/Grandthrax/SingleSidedCurve/commit/28856ad01e0b507ecbc55c5c53e64ee8c875aef7

**Comment by poolpitako** [comment]
Reviewed! 👍

**Comment by dougstorm** [comment]
changes look good, we should add a link to the original review for tracking purposes @Grandthrax

**Comment by fameal** [comment]
good for prod?
