### ISSUE TITLE
Pool Strats for USDC and DAI

### ISSUE THREAD

**Issue by dougstorm** [yearn/yearn-strategies#54]
Description: MattDW downgraded pool strats for DAI/USDC vault, reference ticket for [first review](https://github.com/yearn/yearn-strategies/issues/25)

Commit: [TBD](TBD)

Latest Commit: TBD

Tag:

Scope: [faucet interface](https://github.com/Mattdwest/poolTogether/blob/master/interfaces/poolTogether/IPoolFaucet.sol)
[Pool interface](https://github.com/Mattdwest/poolTogether/blob/master/interfaces/poolTogether/IPoolTogether.sol)
[Generalized strategy for dai/usdc/comp/uni](https://github.com/Mattdwest/poolTogether/blob/master/contracts/StrategyPoolTogether.sol)

Repo: https://github.com/Mattdwest/poolTogether/tree/v3_downgrade
[relevant contracts: ](https://docs.pooltogether.com/networks)

Deployed Contract TBD

Review Ongoing By:
- [x] Doug
- [x] Poolpi
- [x] @TheRyanMiller 

Review Completed By:
- [x] Doug
- [ ] Poolpi
- [x] @TheRyanMiller

**Comment by dougstorm** [comment]
Change:

Please change this to '0.3.0' since its the actual settings the stratParams are using for the version

https://github.com/Mattdwest/poolTogether/blob/41061eeb7bc11468e97bc91f9c0eedd299a67653/contracts/BaseStrategyEdited.sol#L202

**Comment by dougstorm** [comment]
Changes are mostly on baseStrategy, everything else looks good.

**Comment by Mattdwest** [comment]
> Change:
> 
> Please change this to '0.3.0' since its the actual settings the stratParams are using for the version
> 
> https://github.com/Mattdwest/poolTogether/blob/41061eeb7bc11468e97bc91f9c0eedd299a67653/contracts/BaseStrategyEdited.sol#L202

Fixed in new commit https://github.com/Mattdwest/poolTogether/commit/c3f5b859626bb5afbc8511c3ad25554982a4bcf2

**Comment by TheRyanMiller** [comment]
Some errors found on test for DAI.
Matt is now fixing some test issues that appear to be result of some address used in `conf.text` which no longer hold tickets. Will re-rerun tests when he's ready.

![image](https://user-images.githubusercontent.com/3812035/113605223-5c7adc00-9614-11eb-81e2-e62d0a9471c9.png)

**Comment by dougstorm** [comment]
Ran the master branch too and found safe math errors and issues in assertions, so test failing may be related to ganache fork state

**Comment by Mattdwest** [comment]
Pushed a new update that resolves all the errors.  The relevant tests are in [this folder](https://github.com/Mattdwest/poolTogether/tree/v3_downgrade/tests/custom/version0_3_0).  The other tests in the repo are not relevant for 0.3.0 downgrade branch

**Comment by dougstorm** [comment]
Strats moved to PROD
