### ISSUE TITLE
SNX staking strategy

### ISSUE THREAD

**Issue by jmonteer** [yearn/yearn-strategies#55]
**Description**: Use SNX to issue sUSD, which will be invested in yearn's sUSD vault
Synthetix rewards with SNX and sUSD fees to stakers. These will be reinvested

**Commit (hash)**: pending

**Tag**: pending

**Repo**: https://github.com/jmonteer/yearnV2-strat-SNX-staking

**Scope**: (List link to files)
- Strategy.sol

**Additional References or Repo** (Link to underlying protocols or relevant documents):
https://github.com/Synthetixio/synthetix

**Deployed Contract** (etherscan link): 

**Protocol Due Diligence Doc** (Optional for already used protocols in yearn):
https://hackmd.io/0w1RZh7DSc27A9EyzlHbJQ

**Review Ongoing By**:
- [x] @dougstorm (https://github.com/dougstorm)
- [x] @orbxball (https://github.com/orbxball)
- [x] @poolpitako   (https://github.com/poolpitako)

**Review Completed By**:
- [x] @dougstorm (https://github.com/dougstorm)
- [x] @orbxball (https://github.com/orbxball)
- [x] @poolpitako   (https://github.com/poolpitako)

**Comment by jmonteer** [comment]
A more detailed explanation of workflow, pitfalls and important details is comming

**Comment by jmonteer** [comment]
More info: https://hackmd.io/0w1RZh7DSc27A9EyzlHbJQ?view

**Comment by dougstorm** [comment]
Comment;

Are these leftover comments pending?

https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L30

https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L32

**Comment by dougstorm** [comment]
Suggestion;

Should this number be an argument on this emergency func so we can tweak it?

https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L102

**Comment by dougstorm** [comment]
Suggestion:

Should we add the `totalDebt` to the event args to check against repaid amount and debt number over time?

https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L325

**Comment by dougstorm** [comment]
Question:

Here we call `burnSusd` to get back some SNX

https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L296

And down the call stack we call this line:

https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L450

is the burn amount possible to be less?

Since here we add it to the repayAmount as if its guaranteed to be the case

https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L299

Or do we need to check the actual amount burned after the side effect?

**Comment by dougstorm** [comment]
Comment:

Is there an argument for making the part of the repayDebt logic extreme case of liquidating want for sUSD to repay 

https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L311

To require an emergency flag additionally? since this piece is in `adjustPosition` this selling to a loss may happen on keeper harvest and may need manual intervention?

**Comment by dougstorm** [comment]
Question;

What happens if `want` amount is not able to match the amountRepay because of price movement?

https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L311

Is the `buySusdWithWant(amountToRepay);` method expecting to get the exact amount that it requested?

**Comment by dougstorm** [comment]
Suggestion:

Add a way to switch dexes in case is needed:

https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L519

See here:

https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/e5d3a99c388f38271d04e38cd2a9238c0f3ceb2c/contracts/StrategyCurveIBVoterProxy.sol#L376

**Comment by dougstorm** [comment]
Question:

Is this a time sensitive function in case of emergency?

https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L81

May need to be modifier `onlyAuthorized` with the caveat that it may need to check for value in case of the unlikely scenario the strategist gets keys stolen and can set this to random value to break the logic

**Comment by dougstorm** [comment]
Question:

Is there a value here that could potentially break the strategy logic? 

https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L92

Thinking about the strategist keys stolen scenario.

**Comment by jmonteer** [comment]
> Question:
> 
> Here we call `burnSusd` to get back some SNX
> 
> https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L296
> 
> And down the call stack we call this line:
> 
> https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L450
> 
> is the burn amount possible to be less?
> 
> Since here we add it to the repayAmount as if its guaranteed to be the case
> 
> https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L299
> 
> Or do we need to check the actual amount burned after the side effect?

According to Synthetix's code, the only way the actual burn amount is less than what we are asking to burn is if our debt is less than the amount we are asking to burn. This is not possible due to the logic in lines of code L270 to L305. 

However, I changed it to check actual amount burned to avoid underflow in the repaidAmount calculation if something changes in Synthetix OR our logic does not contemplate some cases. This is done for extra precaution and taking into account that extra gas used does not have a high impact (as this should not happen too frequently)

**Comment by jmonteer** [comment]
> Comment:
> 
> Is there an argument for making the part of the repayDebt logic extreme case of liquidating want for sUSD to repay
> 
> https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L311
> 
> To require an emergency flag additionally? since this piece is in `adjustPosition` this selling to a loss may happen on keeper harvest and may need manual intervention?

I believe line of code referenced is not the one you are talking about. 

I'd need to think about this emergency flag.

On one hand, adding the emergency flag makes it dependent on gov /strategist /authorized. This means that the strategy could not "react on its own" to a sudden rally in ETH/BTC (debt pool) price (that is the only reason this would happen). It would need for an authorized account to set the emergency flag, maybe making things worse (or leaving the strategy in an unhealthy C-ratio). 

On the other hand, adding the flag could prevent a keep3r to "panic sell" in case of a sudden temporary rally of debt pool value. Also, taking into account that Synthetix allows 3 days to pass after the margin call before any liquidation happens, it should be enough for authorized accounts to act before liquidations happen. 

What do you think @poolpitako ?

**Comment by jmonteer** [comment]
> Question;
> 
> What happens if `want` amount is not able to match the amountRepay because of price movement in the DEX, e.g SNX goes up?
> 
> https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L311
> 
> Is the `buySusdWithWant(amountToRepay);` method expecting to get the exact amount that it requested in sUSD? which may not be the case always depending of slippage and liquidity

I changed this to check if unlockedWant is enough to buy required sUSD. If it is not enough, it will buy max amount of sUSD with the available amount of want.

**Comment by jmonteer** [comment]
> Suggestion:
> 
> Add a way to switch dexes in case is needed to improve slippage:
> 
> https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L519
> 
> See here:
> 
> https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/e5d3a99c388f38271d04e38cd2a9238c0f3ceb2c/contracts/StrategyCurveIBVoterProxy.sol#L376

Is it worth it taking into account the extra gas spent? 

I'll wait for your confirmation and copy IB Curve Voter strat method if you confirm.

**Comment by jmonteer** [comment]
> Question:
> 
> Is this a time sensitive function in case of emergency?
> 
> https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L81
> 
> If yes, then may need to be modifier `onlyAuthorized` or strategist multisig if we think the method is too sensitive to leave available for the strategist only

I am ok switching to onlyAutorized but want to know what @poolpitako thinks.

**Comment by jmonteer** [comment]
> Question:
> 
> Is there a value here that could potentially break the strategy logic or harm the accounting to force a liquidation?
> 
> https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L92
> 
> Thinking about the strategist keys stolen scenario.

In case this is set too high, strategy will not act on debt ratio moves, which may lead to liquidation if the conditions are met (SNX price goes down or debt pool's value goes up).

Here I would suggest two potential solutions: please choose (also, @poolpitako give your opinion)
- Add max minThreshold to something that we consider high enough to avoid frequent readjustments but not high enough to harm too much (e.g. 5e16). This is adding a require() in setter.
- Change modifier to onlyAuthorized?

**Comment by jmonteer** [comment]
Thanks for your review @dougstorm !
I marked with 👍  comments that I consider solved in the `code_review` branch
I marked with 👀  comments that are to be resolved or waiting for your input (or @poolpitako 's). 

In those that involve authorized roles or best practices, I am asking for input from you guys. You have more experience with other vaults and know how yearn wants to behave under certain circumstances.

Thanks again! 🚀 🚀

**Comment by poolpitako** [comment]
> Question:
> 
> Is this a time sensitive function in case of emergency?
> 
> https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L81
> 
> If yes, then may need to be modifier `onlyAuthorized` or strategist multisig if we think the method is too sensitive to leave available for the strategist only

Let's do it strategist ms.

**Comment by poolpitako** [comment]
> Suggestion:
> 
> Add a way to switch dexes in case is needed to improve slippage:
> 
> https://github.com/jmonteer/yearnV2-strat-SNX-staking/blob/4b6e5377a54be8b1073303d081f460161f7e1591/contracts/Strategy.sol#L519
> 
> See here:
> 
> https://github.com/dudesahn/IB-Curve-Voter-Proxy/blob/e5d3a99c388f38271d04e38cd2a9238c0f3ceb2c/contracts/StrategyCurveIBVoterProxy.sol#L376

Just did this change.

**Comment by dougstorm** [comment]
https://github.com/jmonteer/yearnV2-strat-SNX-staking/pull/8

Review and commented on PR

**Comment by orbxball** [comment]
leave comments in original PR, jmonteer/yearnV2-strat-SNX-staking#8

btw, some niceties.
1. while using interface, address is auto-detected. so `Interface(address(0x00...))` can be shortened to `Interface(0x00...)`.
2. while setting `maxReportDelay`, `days`, `hours` keywords are helpful.
3. During `setRouter`,`bool` type argument can match argument name to avoid unexpected `uint` value

**Comment by jmonteer** [comment]
Thanks for your comments @dougstorm @orbxball 

New SNX Vault and 2 strategies (Generic Aave Lender and sUSD minter) have been deployed

Thanks again

**Comment by dougstorm** [comment]
This strategy is experiment ready, closing issue.
